apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - image: k8s-sample-go:latest
        imagePullPolicy: IfNotPresent
        name: sample-app
        # タグ指定するとDocker hubから持ってこようとする
        envFrom:
          - configMapRef:
              name: sample-app
          - secretRef:
              name: sample-app
        resources: {}
        #   requests:
        #     cpu: 1
        #     memory: 4Mi
        # limits:
        #   memory: "128Mi"
        #   cpu: "500m"
        ports:
        - containerPort: 8080
        # 10.96.0.10:53
        # failed to initialize database, got error dial tcp: lookup mysql on 10.96.0.10:53: no such host
