apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
spec:
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - image: k8s-sample-go:minikube
        # imagePullPolicy: Never
        name: sample-app
        # タグ指定するとDocker hubから持ってこようとする
        envFrom:
          - configMapRef:
              name: sample-app
          - secretRef:
              name: sample-app
        resources: {}
          # limits:
          #   memory: "128Mi"
          #   cpu: "500m"
        ports:
        - containerPort: 8080
