# Build Stage
FROM golang:1.20rc3-alpine3.17 as builder
WORKDIR /app
COPY . .
RUN go build -o main cmd/main.go

# Run Stage
FROM alpine:3.16
WORKDIR /app
COPY --from=builder /app/main .
# COPY app.env .
# COPY start.sh .
# COPY wait-for.sh .
# COPY db/migration ./db/migration

EXPOSE 8080
CMD [ "/app/main" ]
# ENTRYPOINT [ "/app/start.sh" ]
