// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package types

import (
	"github.com/takeuchi-shogo/k8s-go-sample/domain/models"
)

type Matches struct {
	ID           string `json:"id"`
	MaleUserID   int    `json:"male_user_id"`
	FemaleUserID int    `json:"female_user_id"`
}

type NewAccounts struct {
	PhoneNumber string `json:"phone_number"`
	Email       string `json:"email"`
	Password    string `json:"password"`
}

type NewBlocks struct {
	Blocking int `json:"blocking"`
	Blocked  int `json:"blocked"`
}

type NewLikes struct {
	ReceiveUserID int `json:"receive_user_id"`
}

type NewLogin struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type NewReports struct {
	ReporterID int    `json:"reporter_id"`
	ReportedID int    `json:"reported_id"`
	Reason     string `json:"reason"`
}

type NewUserSearchFilters struct {
	Gender   *string `json:"gender"`
	Location *string `json:"location"`
}

type NewUsers struct {
	DisplayName string `json:"display_name"`
	ScreenName  string `json:"screen_name"`
	Gender      string `json:"gender"`
}

type NewVerifyEmails struct {
	Email string `json:"email"`
}

type PageInfo struct {
	HasNextPage     bool    `json:"has_next_page"`
	HasPreviousPage bool    `json:"has_previous_page"`
	StartCursor     *string `json:"start_cursor"`
	EndCursor       *string `json:"end_cursor"`
}

type UpdateAccounts struct {
	ID          int    `json:"id"`
	PhoneNumber string `json:"phone_number"`
	Email       string `json:"email"`
	Password    string `json:"password"`
}

type UpdateUserProfiles struct {
	ID         string `json:"id"`
	BodyTypeID int    `json:"body_type_id"`
}

type UpdateUserSearchFilters struct {
	ID              string  `json:"id"`
	Gender          *string `json:"gender"`
	Location        *string `json:"location"`
	Purpose         int     `json:"purpose"`
	HasIntroduction bool    `json:"has_introduction"`
	HeightID        int     `json:"height_id"`
	BodyTypeID      int     `json:"body_type_id"`
	BloodTypeID     int     `json:"blood_type_id"`
	OccupationID    int     `json:"occupation_id"`
	EducationID     int     `json:"education_id"`
	AnnualIncomeID  int     `json:"annual_income_id"`
	SmokingID       int     `json:"smoking_id"`
	DrinkingID      int     `json:"drinking_id"`
}

type UpdateUsers struct {
	DisplayName string `json:"display_name"`
	Gender      string `json:"gender"`
	Age         int    `json:"age"`
	Location    string `json:"location"`
}

type UserConnection struct {
	Edges    []*UserEdge `json:"edges"`
	PageInfo *PageInfo   `json:"page_info"`
}

type UserEdge struct {
	Cursor string                `json:"cursor"`
	Node   *models.ResponseUsers `json:"node"`
}
