// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package types

type Matches struct {
	ID           string `json:"id"`
	MaleUserID   int    `json:"male_user_id"`
	FemaleUserID int    `json:"female_user_id"`
}

type NewAccounts struct {
	PhoneNumber string `json:"phone_number"`
	Email       string `json:"email"`
	Password    string `json:"password"`
}

type NewBlocks struct {
	Blocking int `json:"blocking"`
	Blocked  int `json:"blocked"`
}

type NewReports struct {
	ReporterID int    `json:"reporter_id"`
	ReportedID int    `json:"reported_id"`
	Reason     string `json:"reason"`
}

type NewUsers struct {
	AccountID   int    `json:"account_id"`
	DisplayName string `json:"display_name"`
	SceenName   string `json:"sceen_name"`
	Gender      string `json:"gender"`
}
