CREATE TABLE IF NOT EXISTS `user_search_filters` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`user_id`  int UNSIGNED NOT NULL,
	`gender` varchar(255) NULL,
	`location` varchar(255) NULL,
	`purpose` int UNSIGNED NOT NULL,
	`has_introduction` tinyint UNSIGNED NOT NULL,
	`height_id` int UNSIGNED NOT NULL,
	`body_type_id` int UNSIGNED NOT NULL,
	`blood_type_id` int UNSIGNED NOT NULL,
	`residence_id` int UNSIGNED NOT NULL,
	`hometown_id` int UNSIGNED NOT NULL,
	`occupation_id` int UNSIGNED NOT NULL,
	`education_id` int UNSIGNED NOT NULL,
	`annual_income_id` int UNSIGNED NOT NULL,
	`smoking_id` int UNSIGNED NOT NULL,
	`drinking_id` int UNSIGNED NOT NULL,
	`created_at` int UNSIGNED NOT NULL,
	`updated_at` int UNSIGNED NOT NULL,
	FOREIGN KEY (user_id) REFERENCES users(id),
	UNIQUE(`user_id`),
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
